//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Большая_пачка
{
    using System;
    using System.Collections.Generic;
    
    public partial class История
    {
        public int ID_Истории { get; set; }
        public Nullable<int> ID_Агента { get; set; }
        public Nullable<int> ID_Аналитика { get; set; }
        public string ID_Точки_продажи { get; set; }
        public Nullable<System.DateTime> Дата_продажи { get; set; }
    
        public virtual Агент Агент { get; set; }
        public virtual Аналитик Аналитик { get; set; }
        public virtual Точка_подажи Точка_подажи { get; set; }
    }
}
