//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Большая_пачка
{
    using System;
    using System.Collections.Generic;
    
    public partial class Точка_подажи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Точка_подажи()
        {
            this.История = new HashSet<История>();
        }
    
        public string ID_Точки_продажи { get; set; }
        public string Название_филиала { get; set; }
        public string Тип { get; set; }
        public string Адрес { get; set; }
        public string Номер { get; set; }
        public string Сайт { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<История> История { get; set; }
    }
}
